size: "200x250"
url: "/assets/a4.jpg"
per_page: 16
admin:
  size: "70x70"
  url: "assets/avata.jpg"
role:
  member: 1
  admin: 2
product:
  index:
    size: "250x240"
  show:
    size: "350x400"
  comment:
    avatar_size: "30x30"
suggest:
  index:
    size: "50x50"
zero: 0
avatar:
  url: "avatar.jpg"
image:
  urlfood: "food.jpg"
  urldrink: "drink.jpg"
chatroom: "50311442"
